import {
  columnNumber,
  rowNumber,
  type ColumnNumber,
  type RowNumber,
  type WorksheetId,
} from "../identifiers";
import { brand, type Brand } from "../brand";

export type CellAddress = Readonly<{
  row: RowNumber;
  column: ColumnNumber;
}>;

export type CellId = Brand<string, "CellId">;

export type CellIdParts = Readonly<{
  worksheetId: WorksheetId;
  address: CellAddress;
}>;

export const cellAddress = (row: number, column: number): CellAddress => ({
  row: rowNumber(row),
  column: columnNumber(column),
});

export const columnLabel = (column: ColumnNumber | number): string => {
  let remaining = Number(column);
  let label = "";

  while (remaining > 0) {
    const remainder = (remaining - 1) % 26;
    label = String.fromCharCode(65 + remainder) + label;
    remaining = Math.floor((remaining - 1) / 26);
  }

  return label;
};

export const columnFromLabel = (label: string): ColumnNumber => {
  if (!/^[A-Za-z]+$/.test(label)) {
    throw new Error(`Invalid column label: ${label}`);
  }

  let result = 0;
  for (const character of label.toUpperCase()) {
    result = result * 26 + character.charCodeAt(0) - 64;
  }

  return columnNumber(result);
};

export const formatA1Address = (address: CellAddress): string =>
  `${columnLabel(address.column)}${address.row}`;

export const parseA1Address = (value: string): CellAddress => {
  const match = /^([A-Za-z]+)([1-9]\d*)$/.exec(value);
  if (match === null) {
    throw new Error(`Invalid A1 address: ${value}`);
  }

  const [, columnLabelText, rowText] = match;
  if (columnLabelText === undefined || rowText === undefined) {
    throw new Error(`Invalid A1 address: ${value}`);
  }

  return {
    column: columnFromLabel(columnLabelText),
    row: rowNumber(Number(rowText)),
  };
};

export const cellId = (worksheetId: WorksheetId, address: CellAddress): CellId =>
  brand<string, "CellId">(`${worksheetId}!${formatA1Address(address)}`);

export const cellIdParts = (value: CellId): CellIdParts => {
  const separator = value.indexOf("!");
  if (separator <= 0 || separator === value.length - 1) {
    throw new Error(`Invalid CellId: ${value}`);
  }

  const worksheet = value.slice(0, separator);
  const address = value.slice(separator + 1);

  // CellId is canonical and generated by cellId. The cast avoids a circular
  // dependency from this low-level helper back to the identifier factory.
  return {
    worksheetId: worksheet as WorksheetId,
    address: parseA1Address(address),
  };
};

export const cellAddressEquals = (left: CellAddress, right: CellAddress): boolean =>
  left.row === right.row && left.column === right.column;

export const isAddressWithin = (
  address: CellAddress,
  first: CellAddress,
  second: CellAddress,
): boolean => {
  const minimumRow = Math.min(first.row, second.row);
  const maximumRow = Math.max(first.row, second.row);
  const minimumColumn = Math.min(first.column, second.column);
  const maximumColumn = Math.max(first.column, second.column);

  return (
    address.row >= minimumRow &&
    address.row <= maximumRow &&
    address.column >= minimumColumn &&
    address.column <= maximumColumn
  );
};
